#!/bin/bash

NAMESERVER="ton-ns.example.com"
KEY_PRIV="/etc/slowdns/server.key"
PORT=5300

# Configurer iptables
iptables -I INPUT -p udp --dport $PORT -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports $PORT

# Lancer le serveur SlowDNS
./dns-server -udp :$PORT -privkey-file $KEY_PRIV $NAMESERVER 0.0.0.0:22
